### ISSUE TITLE
SDK build error

### ISSUE THREAD

**Issue by Hiroshi-tnk** [nabeshima/yocta#1]
このまま
bitbake core-image-rt -c populate_sdk
するとerrorで止まります。
SDKビルドではCORE_IMAGE_EXTRA_INSTALLのドライバ群を抜く必要があります。

こんなでよいでしょうか？

**Comment by nabeshima** [comment]
初issue有難うございます！READMEに追記いたします。

**Comment by Hiroshi-tnk** [comment]
bitbake core-image-rt -c populate_sdk

で上記のCORE_IMAGE_EXTRA_INSTALLの内下記をコメントアウトして実行してみたところ
yocta-files, r8168-driver, linux-firmware-ralink

下記添付のようなエラーとなりました。
[log.do_compile.1819.1819.log](https://github.com/nabeshima/yocta/files/2436028/log.do_compile.1819.1819.log)

meta-yoctaとは関係ないところでエラーが出ているように見えますが、問題点わかりますでしょうか？

**Comment by nabeshima** [comment]
READMEは直しました。

エラーについては調査中です。

**Comment by nabeshima** [comment]
> Bus error (core dumped)
> Makefile:383: recipe for target 'subdir-aarch64-softmmu' failed
> make: *** [subdir-aarch64-softmmu] Error 135

このエラーの件ですが、ぱっと調べた限り、NFSなどファイルシステムのエラーっぽいです。VirtualBoxのvboxsfでマウントしたディレクトリで作業していたりするとでるのかもしれません。

もう一度 `bitbake core-image-rt -c populate_sdk` とやっても同じエラーがでますでしょうか？

**Comment by Hiroshi-tnk** [comment]
できるだけ素の状況にするため、
以下の対応をしたのち再度試してみました。
- 以前インストールした ”/opt/poky/2.5.1” があったのでこれを念の為移動。
- bitbake core-image-rt -c cleanall
- build/tmp 削除
- meta-yocta/recipes-core/yocta-files 以下にいくつか追加していたので、元のものに戻す

結果としてはちょっと違うエラーになりました。
[20181005.zip](https://github.com/nabeshima/yocta/files/2448753/20181005.zip)

ここでログの最初の"-j 8"指定がlocal.confにあったのを思い出して、
先のコメントでVirtualBoxの問題があるかもという話があったので、
ためしに
> BB_NUMBER_THREADS = "4"
> PARALLEL_MAKE = "-j 4"

としてみたところ、warningは少し出ますがうまくいきました。
WARNING: core-image-rt-1.0-r0 do_populate_sdk: coreutils.postinst returned 1, marking as unpacked only, configuration required on target.
WARNING: core-image-rt-1.0-r0 do_populate_sdk: Intentionally failing postinstall scriptlets of ['coreutils'] to defer them to first boot is deprecated. Please place them into pkg_postinst_ontarget_${PN} ().
If deferring to first boot wasn't the intent, then scriptlet failure may mean an issue in the recipe, or a regression elsewhere.
Details of the failure are in /home/cyberdyne/yocto/poky-sumo-19.0.1/build/tmp/work/genericx86-poky-linux/core-image-rt/1.0-r0/temp/log.do_populate_sdk.

VMのリソース付与状態によってはで8指定するとキャパ不足からなにかの問題を引き当てるのかもしれません。

**Comment by nabeshima** [comment]
無事に？うまくいったようで良かったです。

きっとVirtualBoxのバグですね…
VirtualBoxのバージョン、CPU割当数、メモリ割当量を教えて頂けますでしょうか？

warningはちょっと不思議ですね。こちらでもclean installをこんど試してみようと思います。

**Comment by nabeshima** [comment]
これが近そう…VirtualBox on Linuxの問題かもしれませんね…
https://e2e.ti.com/support/processors/f/791/t/609491?Linux-AM5728-SDK-build-issue#

**Comment by Hiroshi-tnk** [comment]
メジャーどころの設定は下記の通りです

- VirtualBox 5.2.18 r124319 (Qt5.6.3)
- メインメモリー：2G
- プロセッサ数：1CPU
- 使用率制限：100%
- ストレージ：SATA .vdi
- OS: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-137-generic x86_64)

**Comment by nabeshima** [comment]
ありがとうございます。
自分の環境は、

- VirtualBox 5.2.18 r124319 (Qt5.6.3)
（同じ。ただし on Mac）

- メインメモリー：4G
- プロセッサ数：4CPU
- 使用率制限：100%
- OS: Ubuntu 16.04.5 LTS (ただし32 bit）

という感じなので、CPU割当とメモリ割り当て変えたらいけるかもですね。。

**Comment by Hiroshi-tnk** [comment]
bitbake core-image-rt
も問題なく完了しまし、作成したイメージで正しく起動できました。
ありがとうございます。

(追加した自前インストーラでトラブっていて、最後まではたどり着けていませんが、、、)

**Comment by nabeshima** [comment]
お、良かったです。
自前インストーラの方についても、こちらで対応した方がよいものがあれば別途issueください。
