### ISSUE TITLE
Removable media format trouble 

### ISSUE THREAD

**Issue by Hiroshi-tnk** [nabeshima/yocta#2]
yocta-files/files相当の場所にインストーラ等を追加して作成したイメージをUSBメモリにいれマシンを起動。(ここまではうまくいきました)

そこからSDカード(/dev/sdb*)にインストールを行うため、刺したSDカードに対してフォーマット(parted)しようとしたところ、”使用中なのでできないよ”的なエラーが発生しました。
もちろん当該デバイスはマウントしていません。
mountコマンドでもマウントされていないことを確認しました。

"fsck -f"も試してみましたが"in use"ということでアクセス出来ませんでした。
なにか、自動的にmountする仕組み的なものが有効化されてたりしますでしょうか？

後日になりますが、こちらで追加した部分を元に戻して、単純にfsckできるか試してみます。
まずは、報告まで。

**Comment by nabeshima** [comment]
自動マウントは入っていないはずです。。
もしかして、SDカードは/dev/sda にマウントされていないでしょうか？

**Comment by Hiroshi-tnk** [comment]
/dev/sda は起動用のUSBメモリでした。
/dev/sdb*がインストール対象のSDカードであることは間違いなさそうです。
そして、mountはできるけど、umountしてもfsckやparted、format等ができない(/dev/sdb1 is in use)ようです。

実際のインストーラでpartedを実行した場合のエラーは下記です。

> Partitions 1,2,3,4 on /dev/sdb have been written, but we have been enable to inform the kernel of change, probably because they are in use. As a result, the old partitions will remain in use. You should reboot now before making further changes.
> 
> /dev/sdb1 is apparently in use by the system; will not make a filesystem here!

このメッセージに従って再起動をしても状況は変わりませんでした。

ここで戻って、dmesgで見ると対象のsdb1,2,3,4はマウントされたと出てますがmountコマンドで表示される一覧にそれっぽいものは無いという状況です。
> mounted filesystem with ordered data mode. Opts:(null)

ということで、どこかにマウントされているけど、mountコマンドでは表示されないという状況なのかもしれません。

**Comment by nabeshima** [comment]
エラーメッセージから関連しそうなものを拾ってきました。
いかがでしょうか？
どうもジャーナリング周りのファイルがストレージに残っているとだめなのかも？

https://superuser.com/questions/855547/mounted-filesystem-without-journal-opts-null-while-mounting-ext4-fs
http://irukano.blogspot.com/2011/03/mkfs.html
https://masaru.org/wp/archives/717

**Comment by Hiroshi-tnk** [comment]
どうもlvm関係なさそうです。
parted print では lvm 状態にはなっていませんでした。
yoctoで作ったイメージにはlmv2が入れられなかったので、他のubuntuマシンで実行してみましたがlvmの設定はありませんでした。
parted で rm してみると、先と同じようなエラーが出ましたがprintではでなくなりましたので、パーティションテーブルから削除はできたようです。

そこで、ubuntuマシンの方でparted試してたところ、こちらではエラーが出ず、正常に実行できました。
ということで、yoctoで起動したマシンでのfsck/parted等の”in use”問題が発生するようです。

**Comment by Hiroshi-tnk** [comment]
VirtualBoxに作成したディスクイメージをマウントして、まっさらなイメージを/dev/sdaにつなげてpartedしてみたところ、正常に動作しました。

ubuntuマシンでも正常に扱えるので、インストール用マシンのハードウェアの構成となにか関係があるのかもしれません。

**Comment by nabeshima** [comment]
なるほど。無事に動いたのであればよかったです。あとは無線周りが正しく動いてくれればいいのですが…

**Comment by Hiroshi-tnk** [comment]
いえ。
結局、インストール用マシンでインストーラが動かないということで、まだCFにインストールができなくで実機で試すところまでいってないです。

**Comment by Hiroshi-tnk** [comment]
起動後、parted で rm で削除してから再起動でパーティション作れるようになりました。
ジャーナルのゴミが残っていたようです。
お騒がせしました。
ただし、インストーラがうまく動かないので調査中です。

**Comment by nabeshima** [comment]
インストーラの件は #3 が上がっているのでこちらはcloseします。
