### ISSUE TITLE
No vmlinuz in .hddimg

### ISSUE THREAD

**Issue by Hiroshi-tnk** [nabeshima/yocta#3]
mortyで動いていたインストーラを使ってインストールをすすめていたのですが、イメージ中にvmlinuzがなくなっていました。

yoctビルド上の問題か、なにか他のものに変更になっているのかわかりますでしょうか？

**Comment by nabeshima** [comment]
カーネルイメージのファイル名が、vmlinuzでなくて、bzImageを使うようになったようです。

起動後に、/boot/bzImageというのがあるので、それをgrubの起動パラメータとして渡すようにインストールすればいけると思います。

**Comment by Hiroshi-tnk** [comment]
ありがとうございます。
bzImageで起動するよう設定を変えたところ、無事起動までこぎつけることができました。

**Comment by nabeshima** [comment]
無事にインストール＆起動できたようでよかったです。
